from PyQt5 import QtCore, QtGui, QtWidgets

## Start PyQt Designer Code
class Ui_BrewConfigWindow(object):
    def setupUi(self, BrewConfigWindow):
        BrewConfigWindow.setObjectName("BrewConfigWindow")
        BrewConfigWindow.resize(1024, 600)
        BrewConfigWindow.setMinimumSize(QtCore.QSize(1024, 600))
        BrewConfigWindow.setMaximumSize(QtCore.QSize(1024, 600))
        self.centralwidget = QtWidgets.QWidget(BrewConfigWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")

        ## Mash Tun Temperature
        self.MashTempLayout = QtWidgets.QGridLayout()
        self.MashTempLayout.setContentsMargins(-1, 0, -1, -1)
        self.MashTempLayout.setObjectName("MashTempLayout")
        self.MashTempIncrease = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MashTempIncrease.setFont(font)
        self.MashTempIncrease.setObjectName("MashTempIncrease")
        self.MashTempLayout.addWidget(self.MashTempIncrease, 1, 2, 1, 1)
        self.MashTempLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MashTempLabel.setFont(font)
        self.MashTempLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MashTempLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.MashTempLabel.setObjectName("MashTempLabel")
        self.MashTempLayout.addWidget(self.MashTempLabel, 0, 1, 1, 1)
        self.MashTempDecrease = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MashTempDecrease.setFont(font)
        self.MashTempDecrease.setObjectName("MashTempDecrease")
        self.MashTempLayout.addWidget(self.MashTempDecrease, 1, 0, 1, 1)
        self.MashTempEntry = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.MashTempEntry.setFont(font)
        self.MashTempEntry.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.MashTempEntry.setAutoFillBackground(False)
        self.MashTempEntry.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.MashTempEntry.setMaxLength(3)
        self.MashTempEntry.setAlignment(QtCore.Qt.AlignCenter)
        self.MashTempEntry.setReadOnly(True)
        self.MashTempEntry.setClearButtonEnabled(False)
        self.MashTempEntry.setObjectName("MashTempEntry")
        self.MashTempLayout.addWidget(self.MashTempEntry, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.MashTempLayout, 0, 0, 1, 1)

        ## Hop Cartridge Quantity
        self.HopCatridgeSelectLayout = QtWidgets.QGridLayout()
        self.HopCatridgeSelectLayout.setObjectName("HopCatridgeSelectLayout")
        self.HopCatridgeSelectEntry = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.HopCatridgeSelectEntry.setFont(font)
        self.HopCatridgeSelectEntry.setMaxLength(1)
        self.HopCatridgeSelectEntry.setAlignment(QtCore.Qt.AlignCenter)
        self.HopCatridgeSelectEntry.setReadOnly(True)
        self.HopCatridgeSelectEntry.setObjectName("HopCatridgeSelectEntry")
        self.HopCatridgeSelectLayout.addWidget(self.HopCatridgeSelectEntry, 1, 1, 1, 1)
        self.HopCatridgeSelectDecrease = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.HopCatridgeSelectDecrease.setFont(font)
        self.HopCatridgeSelectDecrease.setObjectName("HopCatridgeSelectDecrease")
        self.HopCatridgeSelectLayout.addWidget(self.HopCatridgeSelectDecrease, 1, 0, 1, 1)
        self.HopCatridgeSelectIncrease = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.HopCatridgeSelectIncrease.setFont(font)
        self.HopCatridgeSelectIncrease.setObjectName("HopCatridgeSelectIncrease")
        self.HopCatridgeSelectLayout.addWidget(self.HopCatridgeSelectIncrease, 1, 2, 1, 1)
        self.HopCatridgeSelectLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.HopCatridgeSelectLabel.setFont(font)
        self.HopCatridgeSelectLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.HopCatridgeSelectLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.HopCatridgeSelectLabel.setObjectName("HopCatridgeSelectLabel")
        self.HopCatridgeSelectLayout.addWidget(self.HopCatridgeSelectLabel, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.HopCatridgeSelectLayout, 0, 1, 1, 1)

        ## Start Brewing Button
        self.BreweButtonLayout = QtWidgets.QGridLayout()
        self.BreweButtonLayout.setContentsMargins(150, 100, 150, 100)
        self.BreweButtonLayout.setVerticalSpacing(6)
        self.BreweButtonLayout.setObjectName("BreweButtonLayout")
        self.StartBrewButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartBrewButton.setMinimumSize(QtCore.QSize(0, 50))
        self.StartBrewButton.setMaximumSize(QtCore.QSize(1000, 50))
        self.StartBrewButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.StartBrewButton.setDefault(False)
        self.StartBrewButton.setFlat(False)
        self.StartBrewButton.setObjectName("StartBrewButton")
        self.BreweButtonLayout.addWidget(self.StartBrewButton, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.BreweButtonLayout, 3, 0, 1, 2)

        ## Hop Cartridge Timing
        self.HopTimingLayout = QtWidgets.QGridLayout()
        self.HopTimingLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.HopTimingLayout.setContentsMargins(-1, 0, -1, -1)
        self.HopTimingLayout.setVerticalSpacing(10)
        self.HopTimingLayout.setObjectName("HopTimingLayout")
        self.Hop4Increase = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop4Increase.setFont(font)
        self.Hop4Increase.setObjectName("Hop4Increase")
        self.HopTimingLayout.addWidget(self.Hop4Increase, 4, 3, 1, 1)
        self.Hop1Label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop1Label.setFont(font)
        self.Hop1Label.setObjectName("Hop1Label")
        self.HopTimingLayout.addWidget(self.Hop1Label, 1, 0, 1, 1)
        self.Hop2Label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop2Label.setFont(font)
        self.Hop2Label.setObjectName("Hop2Label")
        self.HopTimingLayout.addWidget(self.Hop2Label, 2, 0, 1, 1)
        self.Hop3Decrease = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop3Decrease.setFont(font)
        self.Hop3Decrease.setObjectName("Hop3Decrease")
        self.HopTimingLayout.addWidget(self.Hop3Decrease, 3, 1, 1, 1)
        self.Hop5Label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop5Label.setFont(font)
        self.Hop5Label.setObjectName("Hop5Label")
        self.HopTimingLayout.addWidget(self.Hop5Label, 5, 0, 1, 1)
        self.Hop2Entry = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Hop2Entry.setFont(font)
        self.Hop2Entry.setMaxLength(2)
        self.Hop2Entry.setAlignment(QtCore.Qt.AlignCenter)
        self.Hop2Entry.setReadOnly(True)
        self.Hop2Entry.setObjectName("Hop2Entry")
        self.HopTimingLayout.addWidget(self.Hop2Entry, 2, 2, 1, 1)
        self.Hop5Increase = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop5Increase.setFont(font)
        self.Hop5Increase.setObjectName("Hop5Increase")
        self.HopTimingLayout.addWidget(self.Hop5Increase, 5, 3, 1, 1)
        self.Hop1Entry = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Hop1Entry.setFont(font)
        self.Hop1Entry.setMaxLength(2)
        self.Hop1Entry.setAlignment(QtCore.Qt.AlignCenter)
        self.Hop1Entry.setReadOnly(True)
        self.Hop1Entry.setObjectName("Hop1Entry")
        self.HopTimingLayout.addWidget(self.Hop1Entry, 1, 2, 1, 1)
        self.Hop3Label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop3Label.setFont(font)
        self.Hop3Label.setObjectName("Hop3Label")
        self.HopTimingLayout.addWidget(self.Hop3Label, 3, 0, 1, 1)
        self.HopLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.HopLabel.setFont(font)
        self.HopLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.HopLabel.setObjectName("HopLabel")
        self.HopTimingLayout.addWidget(self.HopLabel, 0, 2, 1, 1)
        self.Hop2Increase = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop2Increase.setFont(font)
        self.Hop2Increase.setObjectName("Hop2Increase")
        self.HopTimingLayout.addWidget(self.Hop2Increase, 2, 3, 1, 1)
        self.Hop1Increase = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop1Increase.setFont(font)
        self.Hop1Increase.setObjectName("Hop1Increase")
        self.HopTimingLayout.addWidget(self.Hop1Increase, 1, 3, 1, 1)
        self.Hop5Decrease = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop5Decrease.setFont(font)
        self.Hop5Decrease.setObjectName("Hop5Decrease")
        self.HopTimingLayout.addWidget(self.Hop5Decrease, 5, 1, 1, 1)
        self.Hop5Entry = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Hop5Entry.setFont(font)
        self.Hop5Entry.setMaxLength(2)
        self.Hop5Entry.setAlignment(QtCore.Qt.AlignCenter)
        self.Hop5Entry.setReadOnly(True)
        self.Hop5Entry.setObjectName("Hop5Entry")
        self.HopTimingLayout.addWidget(self.Hop5Entry, 5, 2, 1, 1)
        self.Hop2Decrease = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop2Decrease.setFont(font)
        self.Hop2Decrease.setObjectName("Hop2Decrease")
        self.HopTimingLayout.addWidget(self.Hop2Decrease, 2, 1, 1, 1)
        self.Hop4Decrease = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop4Decrease.setFont(font)
        self.Hop4Decrease.setObjectName("Hop4Decrease")
        self.HopTimingLayout.addWidget(self.Hop4Decrease, 4, 1, 1, 1)
        self.Hop1Decrease = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop1Decrease.setFont(font)
        self.Hop1Decrease.setObjectName("Hop1Decrease")
        self.HopTimingLayout.addWidget(self.Hop1Decrease, 1, 1, 1, 1)
        self.Hop4Entry = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Hop4Entry.setFont(font)
        self.Hop4Entry.setMaxLength(2)
        self.Hop4Entry.setAlignment(QtCore.Qt.AlignCenter)
        self.Hop4Entry.setReadOnly(True)
        self.Hop4Entry.setObjectName("Hop4Entry")
        self.HopTimingLayout.addWidget(self.Hop4Entry, 4, 2, 1, 1)
        self.Hop3Entry = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Hop3Entry.setFont(font)
        self.Hop3Entry.setMaxLength(2)
        self.Hop3Entry.setAlignment(QtCore.Qt.AlignCenter)
        self.Hop3Entry.setReadOnly(True)
        self.Hop3Entry.setObjectName("Hop3Entry")
        self.HopTimingLayout.addWidget(self.Hop3Entry, 3, 2, 1, 1)
        self.Hop3Increase = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop3Increase.setFont(font)
        self.Hop3Increase.setObjectName("Hop3Increase")
        self.HopTimingLayout.addWidget(self.Hop3Increase, 3, 3, 1, 1)
        self.Hop4Label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop4Label.setFont(font)
        self.Hop4Label.setObjectName("Hop4Label")
        self.HopTimingLayout.addWidget(self.Hop4Label, 4, 0, 1, 1)
        self.gridLayout_2.addLayout(self.HopTimingLayout, 2, 0, 1, 2)
        BrewConfigWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BrewConfigWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        BrewConfigWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BrewConfigWindow)
        self.statusbar.setObjectName("statusbar")
        BrewConfigWindow.setStatusBar(self.statusbar)

        self.retranslateUi(BrewConfigWindow)
        QtCore.QMetaObject.connectSlotsByName(BrewConfigWindow)

    def retranslateUi(self, BrewConfigWindow):
        _translate = QtCore.QCoreApplication.translate
        BrewConfigWindow.setWindowTitle(_translate("BrewConfigWindow", "Brew Configuration"))
        self.MashTempIncrease.setText(_translate("BrewConfigWindow", "+"))
        self.MashTempLabel.setText(_translate("BrewConfigWindow", "Mash Temperature (°F)"))
        self.MashTempDecrease.setText(_translate("BrewConfigWindow", "-"))
        self.MashTempEntry.setText(_translate("BrewConfigWindow", "170"))
        self.HopCatridgeSelectEntry.setText(_translate("BrewConfigWindow", "5"))
        self.HopCatridgeSelectDecrease.setText(_translate("BrewConfigWindow", "-"))
        self.HopCatridgeSelectIncrease.setText(_translate("BrewConfigWindow", "+"))
        self.HopCatridgeSelectLabel.setText(_translate("BrewConfigWindow", "Number of hop cartridges"))
        self.StartBrewButton.setText(_translate("BrewConfigWindow", "Start brewing!"))
        self.Hop4Increase.setText(_translate("BrewConfigWindow", "+"))
        self.Hop1Label.setText(_translate("BrewConfigWindow", "Hop #1"))
        self.Hop2Label.setText(_translate("BrewConfigWindow", "Hop #2"))
        self.Hop3Decrease.setText(_translate("BrewConfigWindow", "-"))
        self.Hop5Label.setText(_translate("BrewConfigWindow", "Hop #5"))
        self.Hop2Entry.setText(_translate("BrewConfigWindow", "5"))
        self.Hop5Increase.setText(_translate("BrewConfigWindow", "+"))
        self.Hop1Entry.setText(_translate("BrewConfigWindow", "5"))
        self.Hop3Label.setText(_translate("BrewConfigWindow", "Hop #3"))
        self.HopLabel.setText(_translate("BrewConfigWindow", "Hop timing (minutes)"))
        self.Hop2Increase.setText(_translate("BrewConfigWindow", "+"))
        self.Hop1Increase.setText(_translate("BrewConfigWindow", "+"))
        self.Hop5Decrease.setText(_translate("BrewConfigWindow", "-"))
        self.Hop5Entry.setText(_translate("BrewConfigWindow", "30"))
        self.Hop2Decrease.setText(_translate("BrewConfigWindow", "-"))
        self.Hop4Decrease.setText(_translate("BrewConfigWindow", "-"))
        self.Hop1Decrease.setText(_translate("BrewConfigWindow", "-"))
        self.Hop4Entry.setText(_translate("BrewConfigWindow", "15"))
        self.Hop3Entry.setText(_translate("BrewConfigWindow", "10"))
        self.Hop3Increase.setText(_translate("BrewConfigWindow", "+"))
        self.Hop4Label.setText(_translate("BrewConfigWindow", "Hop #4"))
## End PyQt Designer Code

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BrewConfigWindow = QtWidgets.QMainWindow()
    ui = Ui_BrewConfigWindow()
    ui.setupUi(BrewConfigWindow)
    BrewConfigWindow.show()
    sys.exit(app.exec_())
