# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BrewConfig.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_BrewConfigWindow(object):
    def setupUi(self, BrewConfigWindow):
        BrewConfigWindow.setObjectName("BrewConfigWindow")
        BrewConfigWindow.resize(1024, 600)
        BrewConfigWindow.setMinimumSize(QtCore.QSize(1024, 0))
        BrewConfigWindow.setMaximumSize(QtCore.QSize(1024, 600))
        self.verticalLayout = QtWidgets.QVBoxLayout(BrewConfigWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.HopCartridgeSelectLayout = QtWidgets.QGridLayout()
        self.HopCartridgeSelectLayout.setObjectName("HopCartridgeSelectLayout")
        self.HopCartridgeSelectEntry = QtWidgets.QLineEdit(BrewConfigWindow)
        self.HopCartridgeSelectEntry.setMinimumSize(QtCore.QSize(0, 30))
        self.HopCartridgeSelectEntry.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.HopCartridgeSelectEntry.setFont(font)
        self.HopCartridgeSelectEntry.setMaxLength(1)
        self.HopCartridgeSelectEntry.setAlignment(QtCore.Qt.AlignCenter)
        self.HopCartridgeSelectEntry.setReadOnly(True)
        self.HopCartridgeSelectEntry.setObjectName("HopCartridgeSelectEntry")
        self.HopCartridgeSelectLayout.addWidget(self.HopCartridgeSelectEntry, 1, 1, 1, 1)
        self.HopCartridgeSelectDecrease = QtWidgets.QPushButton(BrewConfigWindow)
        self.HopCartridgeSelectDecrease.setMinimumSize(QtCore.QSize(0, 30))
        self.HopCartridgeSelectDecrease.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.HopCartridgeSelectDecrease.setFont(font)
        self.HopCartridgeSelectDecrease.setObjectName("HopCartridgeSelectDecrease")
        self.HopCartridgeSelectLayout.addWidget(self.HopCartridgeSelectDecrease, 1, 0, 1, 1)
        self.HopCartridgeSelectIncrease = QtWidgets.QPushButton(BrewConfigWindow)
        self.HopCartridgeSelectIncrease.setMinimumSize(QtCore.QSize(0, 30))
        self.HopCartridgeSelectIncrease.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.HopCartridgeSelectIncrease.setFont(font)
        self.HopCartridgeSelectIncrease.setObjectName("HopCartridgeSelectIncrease")
        self.HopCartridgeSelectLayout.addWidget(self.HopCartridgeSelectIncrease, 1, 2, 1, 1)
        self.HopCartridgeSelectLabel = QtWidgets.QLabel(BrewConfigWindow)
        self.HopCartridgeSelectLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.HopCartridgeSelectLabel.setFont(font)
        self.HopCartridgeSelectLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.HopCartridgeSelectLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.HopCartridgeSelectLabel.setObjectName("HopCartridgeSelectLabel")
        self.HopCartridgeSelectLayout.addWidget(self.HopCartridgeSelectLabel, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.HopCartridgeSelectLayout, 0, 1, 1, 1)
        self.MashTempLayout = QtWidgets.QGridLayout()
        self.MashTempLayout.setContentsMargins(-1, 0, -1, -1)
        self.MashTempLayout.setObjectName("MashTempLayout")
        self.MashTempIncrease = QtWidgets.QPushButton(BrewConfigWindow)
        self.MashTempIncrease.setMinimumSize(QtCore.QSize(0, 30))
        self.MashTempIncrease.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MashTempIncrease.setFont(font)
        self.MashTempIncrease.setObjectName("MashTempIncrease")
        self.MashTempLayout.addWidget(self.MashTempIncrease, 1, 2, 1, 1)
        self.MashTempLabel = QtWidgets.QLabel(BrewConfigWindow)
        self.MashTempLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MashTempLabel.setFont(font)
        self.MashTempLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MashTempLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.MashTempLabel.setObjectName("MashTempLabel")
        self.MashTempLayout.addWidget(self.MashTempLabel, 0, 1, 1, 1)
        self.MashTempDecrease = QtWidgets.QPushButton(BrewConfigWindow)
        self.MashTempDecrease.setMinimumSize(QtCore.QSize(0, 30))
        self.MashTempDecrease.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MashTempDecrease.setFont(font)
        self.MashTempDecrease.setObjectName("MashTempDecrease")
        self.MashTempLayout.addWidget(self.MashTempDecrease, 1, 0, 1, 1)
        self.MashTempEntry = QtWidgets.QLineEdit(BrewConfigWindow)
        self.MashTempEntry.setMinimumSize(QtCore.QSize(0, 30))
        self.MashTempEntry.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.MashTempEntry.setFont(font)
        self.MashTempEntry.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.MashTempEntry.setAutoFillBackground(False)
        self.MashTempEntry.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.MashTempEntry.setMaxLength(3)
        self.MashTempEntry.setAlignment(QtCore.Qt.AlignCenter)
        self.MashTempEntry.setReadOnly(True)
        self.MashTempEntry.setClearButtonEnabled(False)
        self.MashTempEntry.setObjectName("MashTempEntry")
        self.MashTempLayout.addWidget(self.MashTempEntry, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.MashTempLayout, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.HopTimingLayout = QtWidgets.QGridLayout()
        self.HopTimingLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.HopTimingLayout.setContentsMargins(-1, 0, -1, -1)
        self.HopTimingLayout.setVerticalSpacing(10)
        self.HopTimingLayout.setObjectName("HopTimingLayout")
        self.Hop4Entry = QtWidgets.QLineEdit(BrewConfigWindow)
        self.Hop4Entry.setMinimumSize(QtCore.QSize(0, 30))
        self.Hop4Entry.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Hop4Entry.setFont(font)
        self.Hop4Entry.setMaxLength(2)
        self.Hop4Entry.setAlignment(QtCore.Qt.AlignCenter)
        self.Hop4Entry.setReadOnly(True)
        self.Hop4Entry.setObjectName("Hop4Entry")
        self.HopTimingLayout.addWidget(self.Hop4Entry, 4, 2, 1, 1)
        self.Hop1Entry = QtWidgets.QLineEdit(BrewConfigWindow)
        self.Hop1Entry.setMinimumSize(QtCore.QSize(0, 30))
        self.Hop1Entry.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Hop1Entry.setFont(font)
        self.Hop1Entry.setMaxLength(2)
        self.Hop1Entry.setAlignment(QtCore.Qt.AlignCenter)
        self.Hop1Entry.setReadOnly(True)
        self.Hop1Entry.setObjectName("Hop1Entry")
        self.HopTimingLayout.addWidget(self.Hop1Entry, 1, 2, 1, 1)
        self.Hop5Entry = QtWidgets.QLineEdit(BrewConfigWindow)
        self.Hop5Entry.setMinimumSize(QtCore.QSize(0, 30))
        self.Hop5Entry.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Hop5Entry.setFont(font)
        self.Hop5Entry.setMaxLength(2)
        self.Hop5Entry.setAlignment(QtCore.Qt.AlignCenter)
        self.Hop5Entry.setReadOnly(True)
        self.Hop5Entry.setObjectName("Hop5Entry")
        self.HopTimingLayout.addWidget(self.Hop5Entry, 5, 2, 1, 1)
        self.Hop3Decrease = QtWidgets.QPushButton(BrewConfigWindow)
        self.Hop3Decrease.setMinimumSize(QtCore.QSize(0, 30))
        self.Hop3Decrease.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop3Decrease.setFont(font)
        self.Hop3Decrease.setObjectName("Hop3Decrease")
        self.HopTimingLayout.addWidget(self.Hop3Decrease, 3, 1, 1, 1)
        self.Hop3Increase = QtWidgets.QPushButton(BrewConfigWindow)
        self.Hop3Increase.setMinimumSize(QtCore.QSize(0, 30))
        self.Hop3Increase.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop3Increase.setFont(font)
        self.Hop3Increase.setObjectName("Hop3Increase")
        self.HopTimingLayout.addWidget(self.Hop3Increase, 3, 3, 1, 1)
        self.Hop1Label = QtWidgets.QLabel(BrewConfigWindow)
        self.Hop1Label.setMinimumSize(QtCore.QSize(80, 30))
        self.Hop1Label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop1Label.setFont(font)
        self.Hop1Label.setObjectName("Hop1Label")
        self.HopTimingLayout.addWidget(self.Hop1Label, 1, 0, 1, 1)
        self.Hop3Label = QtWidgets.QLabel(BrewConfigWindow)
        self.Hop3Label.setMinimumSize(QtCore.QSize(80, 30))
        self.Hop3Label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop3Label.setFont(font)
        self.Hop3Label.setObjectName("Hop3Label")
        self.HopTimingLayout.addWidget(self.Hop3Label, 3, 0, 1, 1)
        self.Hop4Label = QtWidgets.QLabel(BrewConfigWindow)
        self.Hop4Label.setMinimumSize(QtCore.QSize(80, 30))
        self.Hop4Label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop4Label.setFont(font)
        self.Hop4Label.setObjectName("Hop4Label")
        self.HopTimingLayout.addWidget(self.Hop4Label, 4, 0, 1, 1)
        self.Hop5Increase = QtWidgets.QPushButton(BrewConfigWindow)
        self.Hop5Increase.setMinimumSize(QtCore.QSize(0, 30))
        self.Hop5Increase.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop5Increase.setFont(font)
        self.Hop5Increase.setObjectName("Hop5Increase")
        self.HopTimingLayout.addWidget(self.Hop5Increase, 5, 3, 1, 1)
        self.Hop3Entry = QtWidgets.QLineEdit(BrewConfigWindow)
        self.Hop3Entry.setMinimumSize(QtCore.QSize(0, 30))
        self.Hop3Entry.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Hop3Entry.setFont(font)
        self.Hop3Entry.setMaxLength(2)
        self.Hop3Entry.setAlignment(QtCore.Qt.AlignCenter)
        self.Hop3Entry.setReadOnly(True)
        self.Hop3Entry.setObjectName("Hop3Entry")
        self.HopTimingLayout.addWidget(self.Hop3Entry, 3, 2, 1, 1)
        self.Hop4Decrease = QtWidgets.QPushButton(BrewConfigWindow)
        self.Hop4Decrease.setMinimumSize(QtCore.QSize(0, 30))
        self.Hop4Decrease.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop4Decrease.setFont(font)
        self.Hop4Decrease.setObjectName("Hop4Decrease")
        self.HopTimingLayout.addWidget(self.Hop4Decrease, 4, 1, 1, 1)
        self.Hop2Entry = QtWidgets.QLineEdit(BrewConfigWindow)
        self.Hop2Entry.setMinimumSize(QtCore.QSize(0, 30))
        self.Hop2Entry.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Hop2Entry.setFont(font)
        self.Hop2Entry.setMaxLength(2)
        self.Hop2Entry.setAlignment(QtCore.Qt.AlignCenter)
        self.Hop2Entry.setReadOnly(True)
        self.Hop2Entry.setObjectName("Hop2Entry")
        self.HopTimingLayout.addWidget(self.Hop2Entry, 2, 2, 1, 1)
        self.Hop4Increase = QtWidgets.QPushButton(BrewConfigWindow)
        self.Hop4Increase.setMinimumSize(QtCore.QSize(0, 30))
        self.Hop4Increase.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop4Increase.setFont(font)
        self.Hop4Increase.setObjectName("Hop4Increase")
        self.HopTimingLayout.addWidget(self.Hop4Increase, 4, 3, 1, 1)
        self.Hop5Label = QtWidgets.QLabel(BrewConfigWindow)
        self.Hop5Label.setMinimumSize(QtCore.QSize(80, 30))
        self.Hop5Label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop5Label.setFont(font)
        self.Hop5Label.setObjectName("Hop5Label")
        self.HopTimingLayout.addWidget(self.Hop5Label, 5, 0, 1, 1)
        self.Hop2Label = QtWidgets.QLabel(BrewConfigWindow)
        self.Hop2Label.setMinimumSize(QtCore.QSize(80, 30))
        self.Hop2Label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop2Label.setFont(font)
        self.Hop2Label.setObjectName("Hop2Label")
        self.HopTimingLayout.addWidget(self.Hop2Label, 2, 0, 1, 1)
        self.Hop2Decrease = QtWidgets.QPushButton(BrewConfigWindow)
        self.Hop2Decrease.setMinimumSize(QtCore.QSize(0, 30))
        self.Hop2Decrease.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop2Decrease.setFont(font)
        self.Hop2Decrease.setObjectName("Hop2Decrease")
        self.HopTimingLayout.addWidget(self.Hop2Decrease, 2, 1, 1, 1)
        self.Hop5Decrease = QtWidgets.QPushButton(BrewConfigWindow)
        self.Hop5Decrease.setMinimumSize(QtCore.QSize(0, 30))
        self.Hop5Decrease.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop5Decrease.setFont(font)
        self.Hop5Decrease.setObjectName("Hop5Decrease")
        self.HopTimingLayout.addWidget(self.Hop5Decrease, 5, 1, 1, 1)
        self.HopLabel = QtWidgets.QLabel(BrewConfigWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.HopLabel.setFont(font)
        self.HopLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.HopLabel.setObjectName("HopLabel")
        self.HopTimingLayout.addWidget(self.HopLabel, 0, 2, 1, 1)
        self.Hop1Decrease = QtWidgets.QPushButton(BrewConfigWindow)
        self.Hop1Decrease.setMinimumSize(QtCore.QSize(0, 30))
        self.Hop1Decrease.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop1Decrease.setFont(font)
        self.Hop1Decrease.setObjectName("Hop1Decrease")
        self.HopTimingLayout.addWidget(self.Hop1Decrease, 1, 1, 1, 1)
        self.Hop2Increase = QtWidgets.QPushButton(BrewConfigWindow)
        self.Hop2Increase.setMinimumSize(QtCore.QSize(0, 30))
        self.Hop2Increase.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop2Increase.setFont(font)
        self.Hop2Increase.setObjectName("Hop2Increase")
        self.HopTimingLayout.addWidget(self.Hop2Increase, 2, 3, 1, 1)
        self.Hop1Increase = QtWidgets.QPushButton(BrewConfigWindow)
        self.Hop1Increase.setMinimumSize(QtCore.QSize(0, 30))
        self.Hop1Increase.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hop1Increase.setFont(font)
        self.Hop1Increase.setObjectName("Hop1Increase")
        self.HopTimingLayout.addWidget(self.Hop1Increase, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.HopTimingLayout)
        self.BreweButtonLayout = QtWidgets.QGridLayout()
        self.BreweButtonLayout.setContentsMargins(150, 30, 150, 0)
        self.BreweButtonLayout.setVerticalSpacing(30)
        self.BreweButtonLayout.setObjectName("BreweButtonLayout")
        self.StartBrewButton = QtWidgets.QPushButton(BrewConfigWindow)
        self.StartBrewButton.setMinimumSize(QtCore.QSize(0, 50))
        self.StartBrewButton.setMaximumSize(QtCore.QSize(1000, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.StartBrewButton.setFont(font)
        self.StartBrewButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.StartBrewButton.setDefault(False)
        self.StartBrewButton.setFlat(False)
        self.StartBrewButton.setObjectName("StartBrewButton")
        self.BreweButtonLayout.addWidget(self.StartBrewButton, 0, 0, 1, 1)
        self.BackButton = QtWidgets.QPushButton(BrewConfigWindow)
        self.BackButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BackButton.setFont(font)
        self.BackButton.setObjectName("BackButton")
        self.BreweButtonLayout.addWidget(self.BackButton, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(100)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.QBLoadButton = QtWidgets.QPushButton(BrewConfigWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.QBLoadButton.setFont(font)
        self.QBLoadButton.setCheckable(False)
        self.QBLoadButton.setChecked(False)
        self.QBLoadButton.setObjectName("QBLoadButton")
        self.horizontalLayout_2.addWidget(self.QBLoadButton)
        self.QBDeleteButton = QtWidgets.QPushButton(BrewConfigWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.QBDeleteButton.setFont(font)
        self.QBDeleteButton.setObjectName("QBDeleteButton")
        self.horizontalLayout_2.addWidget(self.QBDeleteButton)
        self.QBSaveButton = QtWidgets.QPushButton(BrewConfigWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.QBSaveButton.setFont(font)
        self.QBSaveButton.setCheckable(False)
        self.QBSaveButton.setObjectName("QBSaveButton")
        self.horizontalLayout_2.addWidget(self.QBSaveButton)
        self.BreweButtonLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.QBComboBox = QtWidgets.QComboBox(BrewConfigWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QBComboBox.sizePolicy().hasHeightForWidth())
        self.QBComboBox.setSizePolicy(sizePolicy)
        self.QBComboBox.setMaximumSize(QtCore.QSize(400, 16777215))
        self.QBComboBox.setObjectName("QBComboBox")
        self.horizontalLayout.addWidget(self.QBComboBox)
        self.BreweButtonLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.BreweButtonLayout)

        self.retranslateUi(BrewConfigWindow)
        QtCore.QMetaObject.connectSlotsByName(BrewConfigWindow)

    def retranslateUi(self, BrewConfigWindow):
        _translate = QtCore.QCoreApplication.translate
        BrewConfigWindow.setWindowTitle(_translate("BrewConfigWindow", "Form"))
        self.HopCartridgeSelectEntry.setText(_translate("BrewConfigWindow", "5"))
        self.HopCartridgeSelectDecrease.setText(_translate("BrewConfigWindow", "-"))
        self.HopCartridgeSelectIncrease.setText(_translate("BrewConfigWindow", "+"))
        self.HopCartridgeSelectLabel.setText(_translate("BrewConfigWindow", "Number of hop cartridges"))
        self.MashTempIncrease.setText(_translate("BrewConfigWindow", "+"))
        self.MashTempLabel.setText(_translate("BrewConfigWindow", "Mash Temperature (°F)"))
        self.MashTempDecrease.setText(_translate("BrewConfigWindow", "-"))
        self.MashTempEntry.setText(_translate("BrewConfigWindow", "170"))
        self.Hop4Entry.setText(_translate("BrewConfigWindow", "15"))
        self.Hop1Entry.setText(_translate("BrewConfigWindow", "5"))
        self.Hop5Entry.setText(_translate("BrewConfigWindow", "30"))
        self.Hop3Decrease.setText(_translate("BrewConfigWindow", "-"))
        self.Hop3Increase.setText(_translate("BrewConfigWindow", "+"))
        self.Hop1Label.setText(_translate("BrewConfigWindow", "Hop #1"))
        self.Hop3Label.setText(_translate("BrewConfigWindow", "Hop #3"))
        self.Hop4Label.setText(_translate("BrewConfigWindow", "Hop #4"))
        self.Hop5Increase.setText(_translate("BrewConfigWindow", "+"))
        self.Hop3Entry.setText(_translate("BrewConfigWindow", "10"))
        self.Hop4Decrease.setText(_translate("BrewConfigWindow", "-"))
        self.Hop2Entry.setText(_translate("BrewConfigWindow", "5"))
        self.Hop4Increase.setText(_translate("BrewConfigWindow", "+"))
        self.Hop5Label.setText(_translate("BrewConfigWindow", "Hop #5"))
        self.Hop2Label.setText(_translate("BrewConfigWindow", "Hop #2"))
        self.Hop2Decrease.setText(_translate("BrewConfigWindow", "-"))
        self.Hop5Decrease.setText(_translate("BrewConfigWindow", "-"))
        self.HopLabel.setText(_translate("BrewConfigWindow", "Hop timing (minutes)"))
        self.Hop1Decrease.setText(_translate("BrewConfigWindow", "-"))
        self.Hop2Increase.setText(_translate("BrewConfigWindow", "+"))
        self.Hop1Increase.setText(_translate("BrewConfigWindow", "+"))
        self.StartBrewButton.setText(_translate("BrewConfigWindow", "Start brewing!"))
        self.BackButton.setText(_translate("BrewConfigWindow", "Back to Main Menu"))
        self.QBLoadButton.setText(_translate("BrewConfigWindow", "Load Quick Brew"))
        self.QBDeleteButton.setText(_translate("BrewConfigWindow", "Delete Quick Brew"))
        self.QBSaveButton.setText(_translate("BrewConfigWindow", "Save Quick Brew"))
